from __future__ import annotations

ADMIN_PAGE = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Telegram Reader — управление чатами</title>
<style>
body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;max-width:980px;margin:32px auto;padding:0 16px;color:#1f2328}
h1{font-size:24px;margin-bottom:6px}.muted{color:#667085;line-height:1.45}.bar{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}
input,button{font:inherit;padding:9px 11px;border:1px solid #cfd4dc;border-radius:8px}input[type=search]{flex:1;min-width:240px}
button{cursor:pointer;background:#fff}button.primary{background:#1677ff;color:#fff;border-color:#1677ff}button.danger{color:#b42318}button:disabled{cursor:not-allowed;opacity:.6}
.status{margin:12px 0;padding:10px 12px;border-radius:8px;font-weight:600;min-height:20px}.status.info{background:#f8fafc;color:#344054;border:1px solid #e2e8f0}.status.ok{background:#ecfdf3;color:#067647;border:1px solid #abefc6}.status.error{background:#fef3f2;color:#b42318;border:1px solid #fecdca}
.list{border:1px solid #e2e5e9;border-radius:10px;overflow:hidden}.row{display:grid;grid-template-columns:34px 1fr auto;gap:8px;align-items:center;padding:10px 12px;border-bottom:1px solid #eef0f2}.row:last-child{border-bottom:0}
.title{font-weight:600}.meta{font-size:12px;color:#667085}.pill{font-size:12px;background:#f2f4f7;padding:3px 7px;border-radius:999px}.hidden{display:none}
.notice{background:#f8fafc;border:1px solid #e2e8f0;border-radius:9px;padding:10px 12px;margin:14px 0;font-size:14px;line-height:1.45}.auth-help{font-size:13px;color:#667085;margin-top:-8px;line-height:1.4}
#key.bad{border-color:#f04438;box-shadow:0 0 0 2px rgba(240,68,56,.12)}
</style></head><body>
<h1>Telegram Reader — управление чатами</h1>
<div class="muted">Галочка означает: ChatGPT разрешено читать этот Telegram-чат через Reader. Снятая галочка запрещает дальнейшее чтение. Изменения начинают действовать после нажатия «Сохранить изменения».</div>
<div class="notice">Список сохраняется постоянно в защищённом хранилище Yandex Cloud и применяется ко всем новым запросам Reader, в том числе после его перезапуска.</div>
<div id="auth">
  <div class="bar"><input id="key" type="password" autocomplete="current-password" placeholder="Ключ управления" onkeydown="if(event.key==='Enter')login()"><button id="loginBtn" class="primary" onclick="login()">Открыть список</button></div>
  <div class="auth-help">Важно: старый ключ из прежней VM-версии может больше не действовать. Текущий ключ хранится в Yandex Lockbox: секрет <b>telegram-reader-serverless-runtime</b>, поле <b>MANAGE_BROWSER_KEY</b>.</div>
</div>
<div id="status" class="status info" role="status" aria-live="polite">Введите действующий ключ управления и нажмите «Открыть список».</div>
<div id="app" class="hidden">
  <div class="bar"><input id="q" type="search" placeholder="Поиск по названию" oninput="render()"><button onclick="selectAll()">Выбрать все</button><button onclick="selectNone()">Снять все</button><button id="reloadBtn" onclick="reload()">Обновить</button><button id="saveBtn" class="primary" onclick="save()">Сохранить изменения</button><button class="danger" onclick="forgetKey()">Забыть ключ на этом компьютере</button></div>
  <div id="list" class="list"></div>
</div>
<script>
let token=localStorage.getItem('tg_admin_token')||'';let dialogs=[];let selected=new Set();let busy=false;
const qp=new URLSearchParams(location.search);if(qp.get('token')){token=qp.get('token').trim();if(token){localStorage.setItem('tg_admin_token',token)}history.replaceState({},'',location.pathname)}
function setBusy(v){busy=v;for(const id of ['loginBtn','reloadBtn','saveBtn']){const b=document.getElementById(id);if(b)b.disabled=v}}
function setStatus(s,type='info'){const e=document.getElementById('status');e.textContent=s;e.className='status '+type}
function explainNetworkError(e){if(e&&e.name==='AbortError')return 'Загрузка заняла слишком много времени. Повторите попытку.';if(e instanceof TypeError)return 'Не удалось связаться с Telegram Reader. Проверьте соединение и повторите попытку.';return e&&e.message?e.message:String(e)}
async function api(path,opt={}){const c=new AbortController();const timer=setTimeout(()=>c.abort(),65000);try{opt.signal=c.signal;opt.headers={...(opt.headers||{}),'X-Admin-Token':token,'Content-Type':'application/json'};const r=await fetch(path,opt);if(r.status===401||r.status===403)throw new Error('Ключ управления не принят. Старый пароль из прежней версии Reader больше не подходит — используйте текущий MANAGE_BROWSER_KEY из Yandex Lockbox.');if(!r.ok){let text=await r.text();if(r.status===400&&text.includes('AT_LEAST_ONE_CHAT_REQUIRED'))throw new Error('Нужно оставить разрешённым хотя бы один чат.');if(r.status===504)throw new Error('Telegram не ответил вовремя. Нажмите «Обновить» ещё раз.');if(r.status===503)throw new Error('Reader временно не может подключиться к Telegram или защищённому хранилищу.');throw new Error(text||('HTTP '+r.status))}return r.json()}finally{clearTimeout(timer)}}
async function login(){if(busy)return;token=document.getElementById('key').value.trim();document.getElementById('key').classList.remove('bad');if(!token){setStatus('Введите ключ управления.','error');document.getElementById('key').classList.add('bad');return}localStorage.setItem('tg_admin_token',token);setStatus('Проверяю ключ и загружаю список Telegram-чатов…','info');await reload(true)}
async function reload(fromLogin=false){if(busy)return;setBusy(true);try{setStatus(fromLogin?'Проверяю ключ и загружаю список Telegram-чатов…':'Обновляю список Telegram-чатов…','info');const data=await api('/api/admin/dialogs');dialogs=Array.isArray(data.dialogs)?data.dialogs:[];selected=new Set(Array.isArray(data.selected)?data.selected:[]);document.getElementById('auth').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('key').classList.remove('bad');render();setStatus('Доступ подтверждён. Разрешено: '+selected.size+' из '+dialogs.length+' чат(ов).','ok')}catch(e){const message=explainNetworkError(e);if(message.includes('Ключ управления не принят')){localStorage.removeItem('tg_admin_token');token='';document.getElementById('key').classList.add('bad')}document.getElementById('auth').classList.remove('hidden');document.getElementById('app').classList.add('hidden');setStatus(message,'error')}finally{setBusy(false)}}
function render(){const q=document.getElementById('q').value.toLowerCase();const box=document.getElementById('list');box.innerHTML='';const visible=dialogs.filter(x=>(x.title||'').toLowerCase().includes(q));if(!visible.length){const empty=document.createElement('div');empty.className='row';empty.textContent=dialogs.length?'По вашему поиску ничего не найдено.':'Telegram-чаты не получены.';box.append(empty);return}for(const d of visible){const row=document.createElement('label');row.className='row';const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.has(d.chat_id);cb.onchange=()=>{cb.checked?selected.add(d.chat_id):selected.delete(d.chat_id);setStatus('Выбрано: '+selected.size+' из '+dialogs.length+' чат(ов). Изменения ещё не сохранены.','info')};const mid=document.createElement('div');mid.innerHTML='<div class="title"></div><div class="meta"></div>';mid.children[0].textContent=d.title||String(d.chat_id);mid.children[1].textContent=(d.username?'@'+d.username+' · ':'')+'ID '+d.chat_id;const pill=document.createElement('span');pill.className='pill';pill.textContent=d.type||'chat';row.append(cb,mid,pill);box.append(row)}}
function selectAll(){selected=new Set(dialogs.map(d=>d.chat_id));render();setStatus('Выбрано: '+selected.size+' из '+dialogs.length+' чат(ов). Изменения ещё не сохранены.','info')}
function selectNone(){selected.clear();render();setStatus('Выбрано: 0 из '+dialogs.length+'. Для сохранения нужно выбрать хотя бы один чат.','error')}
async function save(){if(busy)return;if(selected.size<1){setStatus('Нельзя сохранить пустой список. Выберите хотя бы один Telegram-чат.','error');return}setBusy(true);try{setStatus('Сохраняю выбранные чаты…','info');const r=await api('/api/admin/whitelist',{method:'POST',body:JSON.stringify({chat_ids:[...selected]})});setStatus('Сохранено успешно. ChatGPT разрешено читать '+r.allowed_chats+' чат(ов). Изменение уже действует.','ok')}catch(e){setStatus(explainNetworkError(e),'error')}finally{setBusy(false)}}
function forgetKey(){localStorage.removeItem('tg_admin_token');token='';document.getElementById('key').value='';document.getElementById('key').classList.remove('bad');document.getElementById('app').classList.add('hidden');document.getElementById('auth').classList.remove('hidden');setStatus('Ключ удалён только из этого браузера. Введите действующий MANAGE_BROWSER_KEY для нового входа.','info')}
if(token){document.getElementById('key').value=token;reload(true)}
</script></body></html>'''
